### ISSUE TITLE
Error with `react` packument

### ISSUE THREAD

**Issue by gabelluardo** [orogene/orogene#189]
`oro view react` launch this error:

```
Error: oro_client::bad_json

  × Received some unexpected JSON. Unable to parse.
  ╰─▶ invalid type: boolean `false`, expected a string at line 1 column 342078
   ╭─[https://registry.npmjs.org/react:1:1]
 1 │ "scheduler":"^0.12.0"},"deprecated":false,"description":"React is a JavaScript l
   ·                                         ▲
   ·                                         ╰── here
   ╰────
```

after some investigation, seems it's generated from here:

https://github.com/orogene/orogene/blob/922e5eb35eaf7f7230db9fbb97bdf7710dd2b3df/crates/oro-client/src/api/packument.rs#L14-L17

---

For example, with `oro view vite`:

```
vite@4.1.4 | Proprietary | deps: 5 | releases: 404

bins: vite

dist
.tarball: https://registry.npmjs.org/vite/-/vite-4.1.4.tgz
.shasum: 170d93bcff97e0ebc09764c053eebe130bfe6ca0
.integrity: sha512-3knk/HsbSTKEin43zHu7jTwYWv81f8kgAL99G5NWBcA1LKvtvcVAC4JjBH1arBunO9kQka+1oGbrMKOjk4ZrBg==
.unpackedSize: 3.19 MB

dependencies:
esbuild: ^0.16.14   fsevents: ~2.3.2   postcss: ^8.4.21   resolve: ^1.22.1   rollup: ^3.10.0

```

**Comment by zkat** [comment]
Oooh.

This is happening because of https://github.com/orogene/orogene/blob/main/crates/oro-common/src/packument.rs#L77-L78 and https://github.com/orogene/orogene/blob/main/crates/oro-common/src/packument.rs#L92-L93, because we're being pretty strict about what that field should look like.

The best fix here is to use a `deserialize_with` argument, kinda like what we do with [`object_or_bust`](https://github.com/orogene/orogene/blob/main/crates/oro-common/src/manifest.rs#L249-L261), and just make `false` be `None`.
