### ISSUE TITLE
Provide a centralised store for deduplication (like pnpm)

### ISSUE THREAD

**Issue by happysalada** [orogene/orogene#278]
What do you think about providing an option to reuse packages from a local store and symlinks to the node_modules directory.
The main benefit being much smaller disk usage for people having multiple projects with common packages on their local machine.
It doesnt need to be the default, just having it though would help a lot for people with older machines and too many projects

**Comment by zkat** [comment]
This is already how Orogene works by default:

On systems that don't support Copy-on-Write, a hard link is created from a deduplicated, pre-extracted central cache on your system (meaning, if you have a file with the same hash across many different packages or package versions, that shows up as a single file in the cache, and that single file is linked possibly many times into your `node_modules`). You can disable this behavior with the `--prefer-copy` flag.

On systems that support Copy-on-Write (Linux with Btrfs or Xfs, APFS on macOS, mainly), we do copy-on-write instead of hard linking because it's technically safer than the potential spooky-action-at-a-distance from hard linking.

Additionally, Orogene's default installation mode is basically what PNPM does, as far as having a local store and linking things around within the tree to reduce the number of entries.

Hope this helps :)

**Comment by mon-jai** [comment]
@zkat Does Copy-on-Write work on Windows too?

**Comment by zkat** [comment]
@mon-jai In theory, Windows' new Dev Drive uses ReFS, which is supposed to support Copy on Write, but it didn't seem to work when I tried it. It might not support it, or it might be a bug in the library I'm using for CoW features, which hasn't been updated in a while (and which is supposed to support ReFS).

> Can the cache path be configurated?

Yes, you can use `--cache <path>` or put the following in your [`oro.kdl` config file](https://orogene.dev/book/guide/configuration.html#the-orokdl-config-file):

```kdl
options {
  cache "~/.oro/custom-cache"
}
```

**Comment by zkat** [comment]
If you're interested to look more closely at CoW on Windows, or to subscribe to the relevant issue, check out #275

**Comment by happysalada** [comment]
This is simply amazing, thank you !

**Comment by mon-jai** [comment]
@zkat Thanks.

Does orogene save disk space like pnpm do (having a global store and hard-linking files)? I can't find it in the documentations.

**Comment by zkat** [comment]
@mon-jai yes, that's what I've been saying. Orogene already does this.

**Comment by mon-jai** [comment]
@zkat Thanks. Maybe that could be advertised in Orogene's description too.

**Comment by happysalada** [comment]
I agree with that last comment, that is a big plus and that is what  was preventing me from testing it.
