### ISSUE TITLE
This is a bug with the orogene resolver. Please report it.

### ISSUE THREAD

**Issue by mon-jai** [orogene/orogene#287]
Repo: https://github.com/mon-jai/instagram-export/tree/4b5ab3a300b42e05cd560f664e6ac282d0ba3d80

Orogene emits error and takes quite long to extract the last 20 packages.

```
> oro apply
ERROR clobbered https://registry.npmjs.org/string-width/-/string-width-5.1.2.tgz with https://registry.npmjs.org/string-width/-/string-width-4.2.3.tgz (requested: string-width-cjs@npm:string-width@>=4.2.0 <5.0.0-0). This is a bug with the orogene resolver. Please report it.
ERROR clobbered https://registry.npmjs.org/strip-ansi/-/strip-ansi-7.1.0.tgz with https://registry.npmjs.org/strip-ansi/-/strip-ansi-6.0.1.tgz (requested: strip-ansi-cjs@npm:strip-ansi@>=6.0.1 <7.0.0-0). This is a bug with the orogene resolver. Please report it.
ERROR clobbered https://registry.npmjs.org/wrap-ansi/-/wrap-ansi-8.1.0.tgz with https://registry.npmjs.org/wrap-ansi/-/wrap-ansi-7.0.0.tgz (requested: wrap-ansi-cjs@npm:wrap-ansi@>=7.0.0 <8.0.0-0). This is a bug with the orogene resolver. Please report it.
 WARN deprecated querystring@0.2.0: "The querystring API is considered Legacy. new code should use the URLSearchParams API instead."
 WARN deprecated querystring@0.2.0: "The querystring API is considered Legacy. new code should use the URLSearchParams API instead."
 WARN deprecated @npmcli/move-file@1.1.2: "This functionality has been moved to @npmcli/fs"
 WARN deprecated readdir-scoped-modules@1.1.0: "This functionality has been moved to @npmcli/fs"
 WARN deprecated @npmcli/move-file@1.1.2: "This functionality has been moved to @npmcli/fs"
 WARN deprecated @npmcli/move-file@2.0.1: "This functionality has been moved to @npmcli/fs"
 WARN deprecated debuglog@1.0.1: "Package no longer supported. Contact Support at https://www.npmjs.com/support for more info."
 INFO 🔍 Resolved 980 packages in 6.927s.
 INFO 🧹 Pruned 0 packages in 29.978s.
 INFO 📦 Extracted 977 packages in 1153.644s.
 INFO 🏃 Ran lifecycle scripts in 1.329s.
 INFO 📝 Wrote lockfile to package-lock.kdl.
 INFO 🎉 Applied node_modules/ in 1191.998s. Are we JavaScript yet?
```

**Comment by mon-jai** [comment]
Generated `package-lock.kdl`

https://gist.github.com/mon-jai/9723f680684896c6b2cce9ce498437ba

**Comment by zkat** [comment]
I'm starting to look into this finally, sorry for the delay. 

As far as investigating the performance issue, can you tell me what platform you're on? Anything interesting about your file system, etc?

**Comment by zkat** [comment]
Investigation so far: I can definitely repro this as long as I'm trying to use the existing package-lock.json. Nothing bad happens if I generate a package-lock.kdl normally with a full resolve. 

What this tells me is that the "fast path" lockfile entry loading isn't verifying the entries/their location in the tree, and also possibly we're trying to put them in the wrong place (or even reading the lockfile wrong?)

Will continue investigating.

**Comment by zkat** [comment]
Fixed! It turned out that we were handling aliases wrong all along?! (as in, `foo@npm:bar@^1.2.3`). This is fixed now and will be available in the next release.

Thanks again for reporting this! I can't believe it took me so long to find what was going on. I kept thinking it was something more complicated but it turned out to be a pretty simple oversight.
